"""empty message

Revision ID: 25743e5f94ce
Revises: 03ae470808ea
Create Date: 2021-01-30 11:32:52.945137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25743e5f94ce'
down_revision = '03ae470808ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('img_url', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('venues', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'lng')
    op.drop_column('venues', 'lat')
    op.drop_column('venues', 'img_url')
    # ### end Alembic commands ###
