"""empty message

Revision ID: 32d0455d794d
Revises: ef7d9ff74913
Create Date: 2021-01-26 17:24:14.032055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d0455d794d'
down_revision = 'ef7d9ff74913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('city', sa.String(), nullable=False))
    op.add_column('venues', sa.Column('state', sa.String(), nullable=False))
    op.add_column('venues', sa.Column(
        'street_address', sa.String(), nullable=False))
    op.add_column('venues', sa.Column('img_url', sa.String()))
    op.add_column('venues', sa.Column('lat', sa.Float()))
    op.add_column('venues', sa.Column('lng', sa.Float()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('venues', 'lng')
    op.drop_column('venues', 'lat')
    op.drop_column('venues', 'img_url')
    op.drop_column('venues', 'street_address')
    op.drop_column('venues', 'state')
    op.drop_column('venues', 'city')
    # ### end Alembic commands ###
