"""empty message

Revision ID: 6c8931e1cde4
Revises: 32d0455d794d
Create Date: 2021-01-30 14:31:35.651978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8931e1cde4'
down_revision = '32d0455d794d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'owner_id')
    # ### end Alembic commands ###
