"""empty message

Revision ID: e2d2bd7b0272
Revises: fc740b65792a
Create Date: 2021-02-01 11:03:31.720733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d2bd7b0272'
down_revision = 'fc740b65792a'
branch_labels = None
depends_on = None


# def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
# op.add_column('venues', sa.Column('lat', sa.Float(), nullable=True))
# op.add_column('venues', sa.Column('lng', sa.Float(), nullable=True))
# ### end Alembic commands ###


# def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
# op.drop_column('venues', 'lng')
# op.drop_column('venues', 'lat')
# ### end Alembic commands ###
